Repository sonata-project/SonataSeoBundle, pull requests merged in 2021-09, with the labels that each got.

#568 Manual merge
  .php-cs-fixer.dist.php
  tests/Block/Breadcrumb/BreadcrumbTest.php
  tests/Block/Social/FacebookLikeBoxBlockServiceTest.php
  tests/Block/Social/FacebookLikeButtonBlockServiceTest.php
  tests/Block/Social/FacebookSendButtonBlockServiceTest.php
  tests/Block/Social/FacebookShareButtonBlockServiceTest.php
  tests/Block/Social/TwitterEmbedTweetBlockServiceTest.php
  tests/DependencyInjection/Compiler/ServiceCompilerPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataSeoExtensionTest.php
  tests/Seo/SeoPageTest.php
  tests/Twig/Extension/SeoExtensionTest.php
Labels: pedantic

#571 Remove social blocks
  UPGRADE-3.0.md
  composer.json
  docs/index.rst
  docs/reference/social_blocks.rst
  src/Block/Social/BaseFacebookSocialPluginsBlockService.php
  src/Block/Social/BaseTwitterButtonBlockService.php
  src/Block/Social/EmailShareButtonBlockService.php
  src/Block/Social/FacebookLikeBoxBlockService.php
  src/Block/Social/FacebookLikeButtonBlockService.php
  src/Block/Social/FacebookSendButtonBlockService.php
  src/Block/Social/FacebookShareButtonBlockService.php
  src/Block/Social/PinterestPinButtonBlockService.php
  src/Block/Social/TwitterEmbedTweetBlockService.php
  src/Block/Social/TwitterFollowButtonBlockService.php
  src/Block/Social/TwitterHashtagButtonBlockService.php
  src/Block/Social/TwitterMentionButtonBlockService.php
  src/Block/Social/TwitterShareButtonBlockService.php
  src/Resources/config/blocks.xml
  src/Resources/views/Block/_facebook_sdk.html.twig
  src/Resources/views/Block/_pinterest_sdk.html.twig
  src/Resources/views/Block/_twitter_sdk.html.twig
  src/Resources/views/Block/block_email_share_button.html.twig
  src/Resources/views/Block/block_facebook_like_box.html.twig
  src/Resources/views/Block/block_facebook_like_button.html.twig
  src/Resources/views/Block/block_facebook_send_button.html.twig
  src/Resources/views/Block/block_facebook_share_button.html.twig
  src/Resources/views/Block/block_pinterest_pin_button.html.twig
  src/Resources/views/Block/block_social_container.html.twig
  src/Resources/views/Block/block_twitter_embed.html.twig
  src/Resources/views/Block/block_twitter_follow_button.html.twig
  src/Resources/views/Block/block_twitter_hashtag_button.html.twig
  src/Resources/views/Block/block_twitter_mention_button.html.twig
  src/Resources/views/Block/block_twitter_share_button.html.twig
  src/Resources/views/Default/index.html.twig
  tests/Block/Social/FacebookLikeBoxBlockServiceTest.php
  tests/Block/Social/FacebookLikeButtonBlockServiceTest.php
  tests/Block/Social/FacebookSendButtonBlockServiceTest.php
  tests/Block/Social/FacebookShareButtonBlockServiceTest.php
  tests/Block/Social/TwitterEmbedTweetBlockServiceTest.php
  tests/Fixtures/TwitterEmbedTweetBSTest.php
Labels: major

#583 Remove branch alias
  composer.json
Labels: pedantic

#579 Increase phpstan level
  .github/workflows/qa.yml
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm-baseline.xml
  psalm.xml
  src/DependencyInjection/Compiler/ServiceCompilerPass.php
  src/DependencyInjection/SonataSeoExtension.php
  src/Event/BreadcrumbListener.php
  src/Seo/SeoPage.php
  src/Sitemap/SourceManager.php
  tests/Block/Breadcrumb/BreadcrumbTest.php
  tests/DependencyInjection/Compiler/ServiceCompilerPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Seo/SeoPageTest.php
Labels: pedantic

#597 Allow setting global page prefix and suffix
  docs/reference/installation.rst
  src/DependencyInjection/Compiler/ServiceCompilerPass.php
  src/DependencyInjection/Configuration.php
  tests/DependencyInjection/Compiler/ServiceCompilerPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: minor, feature

#588 Add `sonata_seo_breadcrumb` to render current breadcrumb
  docs/reference/breadcrumb.rst
  docs/reference/usage.rst
  src/Resources/views/breadcrumb.html.twig
  src/Seo/SeoPage.php
  src/Seo/SeoPageInterface.php
  src/Twig/Extension/SeoExtension.php
Labels: minor

#596 Add priority for breadcrumb blocks
  docs/reference/breadcrumb.rst
  src/DependencyInjection/Compiler/BreadcrumbBlockServicesCompilerPass.php
  tests/DependencyInjection/Compiler/BreadcrumbBlockServicesCompilerPassTest.php
Labels: minor, feature

#598 Fix null error in SeoPage
  src/Seo/SeoPage.php
Labels: pedantic

#603 Move BreadcrumbInterface
  src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php
  src/Block/Breadcrumb/BreadcrumbBlockService.php
  src/BreadcrumbInterface.php
Labels: minor

#605 Update homepage
  composer.json
Labels: pedantic
