Repository sonata-project/SonataSeoBundle, pull requests merged in 2021-11, with the labels that each got.

#624 Remove `BaseBreadcrumbMenuBlockService::getRootMenu`
  UPGRADE-3.0.md
  src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php
  src/Block/Breadcrumb/HomepageBreadcrumbBlockService.php
  tests/Block/Breadcrumb/BreadcrumbTest.php
Labels: major

#623 Add upgrade information to BaseBreadcrumbMenuBlockService
  src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php
Labels: minor

#625 Make UPGRADE docs more clear
  UPGRADE-3.0.md
Labels: pedantic

#642 Avoid phpstan-return
  src/Sitemap/SourceManager.php
Labels: pedantic
