Repository sonata-project/SonataSeoBundle, pull requests merged in 2023-06, with the labels that each got.

#724 DevKit updates for 3.x branch
  .php-cs-fixer.dist.php
Labels: automerge, dev-kit

#726 Release 3.7.0
  CHANGELOG.md
Labels: dev-kit

#727 DevKit updates for 3.x branch
  .github/FUNDING.yml
Labels: automerge, dev-kit

#728 Fix versions on the upgrade file
  UPGRADE-3.x.md
Labels: pedantic

#729 Update rector
  composer.json
Labels: pedantic
