Repository sonata-project/SonataSeoBundle, pull requests merged in 2023-04, with the labels that each got.

#714 Drop support for Symfony 4 and Twig 2
  .github/workflows/test.yaml
  composer.json
  src/Command/SitemapGeneratorCommand.php
  src/Resources/config/blocks.php
  src/Resources/config/commands.php
  src/Resources/config/event.php
  src/Resources/config/services.php
Labels: minor

#716 DevKit updates for 3.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#718 DevKit updates for 3.x branch
  README.md
Labels: automerge

#719 Fix CHANGELOG
  CHANGELOG.md
Labels: pedantic
