Repository sonata-project/SonataSeoBundle, pull requests merged in 2024-06, with the labels that each got.

#751 Bump rector
  composer.json
Labels: pedantic

#752 DevKit updates for 3.x branch
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#753 Solve usage of internal class
  src/DependencyInjection/SonataSeoExtension.php
Labels: patch
